global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:80']  # Aponta para o contêiner da aplicação

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']  # Aponta para o próprio Prometheus