apiVersion: v1
kind: Service
metadata:
  name: atualizacao-produtor
spec:
  selector:
    app: atualizacao-produtor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP 
