apiVersion: v1
kind: Service
metadata:
  name: atualizacao-consumidor
spec:
  selector:
    app: atualizacao-consumidor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
