apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulta-contato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consulta-contato
  template:
    metadata:
      labels:
        app: consulta-contato
    spec:
      containers:
        - name: consulta-contato
          image: mancinicadu/consulta-contato:1.0
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__ConnectionString
              value: "Server=192.168.0.45\\MSSQLSERVER_FIAP;Database=tech_challenge_1;User Id=fiap_user;Password=1234;TrustServerCertificate=True;"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
