CREATE TABLE
Regiao (
Id INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
DataCriacao DATETIME NOT NULL,
RegiaoNome VARCHAR(100) NOT NULL,
RegiaoDdd INT NOT NULL
)

CREATE TABLE
Contato (
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
DataCriacao DATETIME NOT NULL,
ContatoNome VARCHAR(100) NOT NULL,
ContatoTelefone VARCHAR(11) NOT NULL,
ContatoEmail VARCHAR(100) NOT NULL,
RegiaoId INT FOREIGN KEY REFERENCES Regiao(Id)
)