global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5207']  # Aponta para a aplicação rodando no localhost, mapeando a partir do contêiner

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']  # Aponta para o próprio Prometheus
