apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'consulta-contato'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['consulta-contato:80']

      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['rabbitmq-exporter:9419']