apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastro-consumidor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadastro-consumidor
  template:
    metadata:
      labels:
        app: cadastro-consumidor
    spec:
      containers:
        - name: cadastro-consumidor
          image: mancinicadu/cadastro-consumidor:1.0
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__ConnectionString
              value: "Server=192.168.0.45\\MSSQLSERVER_FIAP;Database=tech_challenge_1;User Id=fiap_user;Password=1234;TrustServerCertificate=True;"
            - name: MassTransit__NomeFila
              value: "filaCadastro"
            - name: MassTransit__Servidor
              value: "rabbitmq"
            - name: MassTransit__Usuario
              value: "guest"
            - name: MassTransit__Senha
              value: "guest"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"