name: Build and Test - Atualização

on:
  push:
    paths:
      - 'Atualizacao/**'
      - 'AtualizacaoProdutor/**'
      - 'AtualizacaoConsumidor/**'
  pull_request:
    paths:
      - 'Atualizacao/**'
      - 'AtualizacaoProdutor/**'
      - 'AtualizacaoConsumidor/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore Atualizacao/Atualizacao.csproj
      - name: Build Atualização
        run: dotnet build Atualizacao/Atualizacao.csproj --no-restore
      - name: Test Atualização
        run: dotnet test Atualizacao/Atualizacao.csproj --no-build --verbosity normal
